name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Extract short SHA
        id: sha
        run: echo "::set-output name=short::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: djharshit
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: djharshit
          password: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
      
      - name: Build and push to Docker Hub and GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/djharshit/${{ github.event.repository.name }}:${{ steps.sha.outputs.short }}
            ghcr.io/djharshit/${{ github.event.repository.name }}:${{ steps.sha.outputs.short }}